# This is a sample build configuration for Java (Gradle).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.//forgeti_shatta
image: java:8

pipelines:
  branches:
    master:
      - step:
          caches:
            - gradle
          deployment: test
          script: # Modify the commands below to build your repository.
            # You must commit the Gradle wrapper to your repository
            # https://docs.gradle.org/current/userguide/gradle_wrapper.html
  #           - bash ./gradlew build
             - bash ./gradlew compileJava
             - bash ./gradlew processResources
             - bash ./gradlew classes
             - bash ./gradlew findMainClass
             - bash ./gradlew war
             - bash ./gradlew bootRepackage
             - bash ./gradlew assemble
             - bash ./gradlew compileTestJava
             - bash ./gradlew processTestResources
             - bash ./gradlew testClasses
             - scp build/libs/timetable-technical-kotech.war root@178.79.183.25:/opt/tomcat/webapps